// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtKCKDHk-FcNWwCxbQJ1AE8lJk5E3i-q4',
    appId: '1:529372324010:web:9a1be828b9f882d7df30d3',
    messagingSenderId: '529372324010',
    projectId: 'voting-61054',
    authDomain: 'voting-61054.firebaseapp.com',
    storageBucket: 'voting-61054.appspot.com',
    measurementId: 'G-NLYSLZQKS9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiWdUv50X7uUXThjgcX6RIOnl8-3sIsQ4',
    appId: '1:529372324010:android:c9644918d64ff947df30d3',
    messagingSenderId: '529372324010',
    projectId: 'voting-61054',
    storageBucket: 'voting-61054.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNeMTP7wjXeK4sKcJQiDULK9cH4zLKZ7c',
    appId: '1:529372324010:ios:a83b54ad4de73609df30d3',
    messagingSenderId: '529372324010',
    projectId: 'voting-61054',
    storageBucket: 'voting-61054.appspot.com',
    iosBundleId: 'com.example.firstapp',
  );
}
